n=int(input())
num=list(map(int,input().split()))
even=0
odd=0
for i in range(n):
    if(num[i]%2==0):even+=1
    else:odd+=1
i=0
while(1):
    if(i%2==0):
        if(even>=1):even-=1
        elif(odd>=2):odd-=2
        else:break
    else:
        if(odd>=1):odd-=1
        else:break
    i+=1
if(odd>0):i-=1
print(i)
